# https://www.nginx.com/resources/wiki/start/topics/examples/full/

user    nginx nginx;
pid     /usr/run/nginx.pid;
worker_process  1;

# [ debug | info | notice | warn | error | crit ]
error_log   /var/log/nginx/error.log info;

events {
    worker_connections  1024;
}

http {
    include         /etc/nginx/mime.types;

    default_type    application/octet-stream;
    charset         utf-8;

    log_format  main '$remote_addr - $remote_user [$time_local]  $status '
        '"$request" $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';

    log_format  download '$remote_addr - $remote_user [$time_local] $status '
        '"$request" $bytes_sent "$http_referer" "$http_user_agent" '
        '"$http_range" "$sent_http_content_range"';

    access_log  /var/log/nginx/access.log main;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;

    keepalive_timeout       65;
    # https://www.nginx.com/resources/wiki/start/topics/examples/full/#proxy-conf
    proxy_redirect          off;
    proxy_set_header        Host              $host; # origin Host
    proxy_set_header        X-Real-IP         $remote_addr; # origin IP
    proxy_set_header        X-Forwarded-For   $proxy_add_x_forwarded_for; # chain of proxy IPs
    proxy_set_header        X-Forwarded-Proto $scheme; # original request http or https

    client_max_body_size    1M;

    server { # Static content provider and default server
        listen      80;
        server_name bloodtestlab.org www.bloodtestlab.org *.bloodtestlab.org;
        root        /var/share/nginx/html;

        error_page 404 444          /40x.html;
        error_page 500 502 503 504  /50x.html;

        location = / {
            index       index.html;
            expires     7d;
        }

        location / {
            index       index.html;
            expires     7d;

            #log_not_found   off;
        }

        location ^~ /(css|js)/ {
            expires     7d;
        }

        location ^~ /image/ {
            root        /home/app-data;
            expires     30d;

            #open_file_cache_errors  off;
        }
    }

    server { # Recording service reverse-proxy
        listen      80;
        server_name api.bloodtestlab.org;
        access_log  /var/log/nginx/recordservice.access.log main;

        location / { # Pass requests to Gunicorn+Flask REST API backend.
            proxy_pass      http://api.bloodtestlab.org:5000;
        }
    }
}
