name: ${COMPOSE_PROJECT_NAME:?"Please, set project name in .env file."}
services:
  backend_mongodb:
    # Add init script to /docker-entrypoint-initdb.d to 'disableTelemetry()' for 'mongosh' or use depricated 'mongo' cli.
    container_name: ${COMPOSE_PROJECT_NAME}_backend_mongodb
    image: mongo:5-focal
    command: -f /etc/mongod.conf --bind_ip localhost,172.28.0.40 --port 27017 --dbpath /data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE:?"MongoDB is not set"}

    cap_drop:
      - ALL
    cap_add:
      - chown
      - setgid
      - setuid
    deploy:
      resources:
        limits:
          memory: ${MONGODB_RAM_LIMIT:-1536M}
        reservations:
          memory: ${MONGODB_RAM_RESERVE:-1024M}
    expose:
      - 27017
    networks:
      backend_network:
        aliases:
          - mongodb.lab.local
        ipv4_address: 172.28.0.40
    restart: ${RESTART_POLICY:-always}
    stop_grace_period: 1m
    user: mongodb

    configs:
      - source: backend_mongodb_config
        target: /etc/mongod.conf
    volumes:
      - type: volume
        source: backend_mongodb_main
        target: /data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      start_period: 60s
      interval: 20s
      retries: 3
      timeout: 3s

  backend_rest:
    container_name: ${COMPOSE_PROJECT_NAME}_backend_rest
    image: voib2lab/rest:latest
    build: ./btestlab-rest
    environment:
      MONGODB_DB: ${MONGODB_DATABASE:?"MongoDB is not set"}
      MONGODB_URI: mongodb://mongodb.lab.local:27017
      SERVER_HOST: 172.28.0.60
      SERVER_PORT: 8080

    cap_drop:
      - ALL
    depends_on:
      backend_mongodb:
        condition: service_healthy
    expose:
      - 8080
    init: true
    networks:
      backend_network:
        aliases:
          - rest.lab.local
        ipv4_address: 172.28.0.60
    restart: ${RESTART_POLICY:-always}
    stop_grace_period: 1m

  webserver:
    container_name: ${COMPOSE_PROJECT_NAME}_webserver
    image: voib2lab/webserver:latest
    build: ./btestlab-webserver

    cap_drop:
      - ALL
    cap_add:
      - chown
      - dac_override
      - net_bind_service
      - setgid
      - setuid
    expose:
      - 80
      - 443
    networks:
      backend_network:
        aliases:
          - lab.local
          - voib2lab.ru
        ipv4_address: 172.28.0.20
    restart: ${RESTART_POLICY:-always}

    configs:
      - source: webserver_config
        target: /etc/nginx/nginx.conf

networks:
  backend_network:
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1

configs:
  backend_mongodb_config:
    file: ./mongo/mongod.conf
  webserver_config:
    file: ./btestlab-webserver/nginx.conf

volumes:
  backend_mongodb_main:
