name: ${COMPOSE_PROJECT_NAME:?"Please, set project name in .env file."}
services:
  backend_api:
    container_name: ${COMPOSE_PROJECT_NAME}_backend_api
    image: btestlab/backend_api:latest
    build: ./btestlab-rest
    environment:
      MONGODB_DB: ${MONGODB_DATABASE:?"MongoDB is not set"}
      MONGODB_URI: mongodb://mongodb.btestlab.local:27017
      SERVER_HOST: 172.20.100.60
      SERVER_PORT: 8080

    cap_drop:
      - ALL
    depends_on:
      backend_db:
        condition: service_healthy
    expose:
      - 8080
    init: true
    networks:
      backend_network:
        aliases:
          - backend.btestlab.local
        ipv4_address: 172.20.100.60
    restart: ${RESTART_POLICY:-always}
    stop_grace_period: 1m

  backend_db:
    container_name: ${COMPOSE_PROJECT_NAME}_backend_db
    image: btestlab/backend_db:latest
    build:
      context: ./mongo
      args:
        BTL_BRANCH: ${BTL_BRANCH:-main}
    command: --bind_ip localhost,172.20.100.40
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE:?"MongoDB is not set"}

    cap_drop:
      - ALL
    cap_add:
      - chown
      - setgid
      - setuid
    deploy:
      resources:
        limits:
          memory: ${MONGODB_RAM_LIMIT:-2048M}
        reservations:
          memory: ${MONGODB_RAM_RESERVE:-1024M}
    expose:
      - 27017
    networks:
      backend_network:
        aliases:
          - mongodb.btestlab.local
        ipv4_address: 172.20.100.40
    restart: ${RESTART_POLICY:-always}
    stop_grace_period: 1m

    volumes:
      - type: volume
        source: backend_mongodb_main
        target: /data/db

  webserver:
    container_name: ${COMPOSE_PROJECT_NAME}_webserver
    image: btestlab/webserver:latest
    build:
      context: ./nginx
      args:
        BTL_BACKEND: backend.btestlab.local:8080
        BTL_DOMAIN: ${BTL_DOMAIN:?"Domain name is not defined"}

    cap_drop:
      - ALL
    cap_add:
      - chown
      - dac_override
      - net_bind_service
      - setgid
      - setuid
    expose:
      - 80
      - 443
    networks:
      backend_network:
        ipv4_address: 172.20.100.20
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    restart: ${RESTART_POLICY:-always}

networks:
  backend_network:
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.20.100.0/24
          gateway: 172.20.100.1

volumes:
  backend_mongodb_main:
